modLoader="javafml"
loaderVersion="[40,)"
license="LGPL-3.0-or-later"

[[mods]]
modId="nounusedchunks"
version="1.0"
displayName="No Unused Chunks"
description="Reduces world size by discarding unused chunks."
logoFile="nounusedchunks_logo.png"
authors="TheCSDev"
credits=""

[[dependencies.nounusedchunks]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nounusedchunks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
